database:
  connectionstrng: 
  containername: resumeshortlisterapp
vectorstore:
  pineconekey: 
  pineconeindex: resumeshortlistervectors
  pineconenamespace: resumeshortlisternamespace
chunking:
  chunkstatagy: recursive
  chunksize: 800
  chunkoverlap: 200
openai:
  key:
  model: gpt-4o
  embeddingmodel: text-embedding-3-large
  vectordimensions: 3072
user:
  defaultuser: john.doe@software.tech
